# -*- coding: utf-8 -*-
"""data science day 2 aingment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uCJY-161-5HrflrX62PCU6_3TyPm-r5w
"""

a = []
for i in range (0,10):
  num = int(input("enter the number "))
  if num % 2 == 0:
    a.append(num)
    print(a)
  else :
    print(a)

"""EXAMPLE OF LIST COMPREHENSION"""

human_letters = [ i for i in 'human' ]
print( human_letters)

d = dict()
n = int(input("take a value "))
for i in range (1, n+1):
  
    d[i]=i**2
print(d)